olajide
### GET REQUEST
POST  http://127.0.0.1:8000/api-v1/join_community/4/
content-type: application/json
Authorization: Token c64b12ff84bd41f761aedd4cd0479209a45d6ffb

# {
#   "body": "i really love to code",
#   "community": 1
# }

olajide
### GET REQUEST
POST  http://127.0.0.1:8000/api-v1/community/4/create-post/
content-type: application/json
Authorization: Token c64b12ff84bd41f761aedd4cd0479209a45d6ffb

{
  "body": " Hi Test Community"
}