olajide
### GET REQUEST
POST  http://127.0.0.1:8000/api-v1/join_community/4/
content-type: application/json
Authorization: Token c64b12ff84bd41f761aedd4cd0479209a45d6ffb

# {
#   "body": "i really love to code",
#   "community": 1
# }

olajide
### GET REQUEST
PUT     http://127.0.0.1:8000/api-v1/job/2/
content-type: application/json
Authorization: Token c64b12ff84bd41f761aedd4cd0479209a45d6ffb

{
    "title": "React Developer",
    "description": "react desc",
    "location": "lagos",
    "salary": "170k - 200k",
    "responsibities": "react res",
    "benefits": "Official Car"
 
}


###
GET   http://127.0.0.1:8000/api-v1/jobs/?title=reactjs%20developer&location=lagos/
content-type: application/json
Authorization: Token c64b12ff84bd41f761aedd4cd0479209a45d6ffb


{
  "body": "i believe the post author will get notified"
}


###
GET   http://127.0.0.1:8000/api-v1/jobs/
content-type: application/json
Authorization: Token 8af888e888fa2d982ccf999f1d66c87d3c4b0187


