### GET REQUEST
GET http://127.0.0.1:8000/accounts/
content-type: application/json
Authorization: Token c50b8856fefa745727755101a11cadab16994d57

### GET REQUEST
POST  http://127.0.0.1:8000/accounts/signup
content-type: application/json

{
    "username": "andrew",
    "password": "Backend@8080",
    "confirm_password": "Backend@8080",
    "email": "andrew@gmail.com"

}

### GET REQUEST
POST  http://127.0.0.1:8000/api-v1/post/like-unlike/1/
content-type: application/json
Authorization: Token c50b8856fefa745727755101a11cadab16994d57


{
     "email": "andrew@gmail",
     "password": "Backend@8080"
}

### GET REQUEST
POST  http://127.0.0.1:8000/api-v1/login/
content-type: application/json

{
     "email": "andrew@gmail",
     "password": "Backend@8080"
}


jendoic
### GET REQUEST
POST  http://127.0.0.1:8000/api-v1/user/3/follow/
content-type: application/json
Authorization: Token c50b8856fefa745727755101a11cadab16994d57



andrew
### GET REQUEST
POST  http://127.0.0.1:8000/api-v1/user/3/follow/
content-type: application/json
Authorization: Token 24dd63a568cce27693b5710d7afd6f8c953e7de0


olajide
### GET REQUEST
GET      http://127.0.0.1:8000/api-v1/bookmarks/
content-type: application/json
Authorization: Token c64b12ff84bd41f761aedd4cd0479209a45d6ffb

{
     "post": 3
}


olajide
### GET REQUEST
GET  http://127.0.0.1:8000/api-v1/community/1/posts/
content-type: application/json
Authorization: Token c64b12ff84bd41f761aedd4cd0479209a45d6ffb





olajide
### GET REQUEST
POST  http://127.0.0.1:8000/api-v1/community/2/create-post/
content-type: application/json
Authorization: Token c64b12ff84bd41f761aedd4cd0479209a45d6ffb




