# Generated by Django 4.2.7 on 2023-12-01 20:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0007_community_members_delete_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(related_name='communities', to=settings.AUTH_USER_MODEL),
        ),
    ]
