# Generated by Django 4.2.7 on 2023-12-04 11:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0012_alter_post_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='CommunityComment',
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='CommunityPost',
        ),
    ]
