# Generated by Django 4.2.7 on 2023-12-04 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0013_rename_comment_communitycomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='kudos',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
