# Generated by Django 4.2.4 on 2023-12-11 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='address_address',
            new_name='physical_address',
        ),
    ]
