# Generated by Django 4.2.7 on 2023-12-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_rename_address_address_event_physical_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_ticket',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_site',
            field=models.URLField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_fee',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='virtual_address',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
