# Generated by Django 4.2.7 on 2023-12-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_cover_picture_event_description_event_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration_site',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='virtual_address',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
