# Generated by Django 4.2.7 on 2023-12-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_end_date_alter_event_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ticket_fee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
