# Generated by Django 4.2.7 on 2023-12-16 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_event_ticket_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='physical_address',
            new_name='Location',
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.DeleteModel(
            name='EventType',
        ),
    ]
