# Generated by Django 4.2.7 on 2023-12-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_rename_physical_address_event_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True),
        ),
    ]
