# Generated by Django 4.2.7 on 2023-12-07 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='user',
            new_name='creator',
        ),
    ]
