# Generated by Django 4.2.7 on 2023-12-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_tag_job_created_job_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag', to='job.tag'),
        ),
    ]
