# Generated by Django 4.2.7 on 2023-12-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_job_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
